### ISSUE TITLE
Description of Tiling Logic?

### ISSUE THREAD

**Issue by caseyjconger** [chrisnorth/Planckoscope#2]
Hi,

I downloaded the tarballed images from the interactive plankoscope website (which is super cool by the way) and just wanted to recreate a flat image. And the website directed here for the code to process the tiled images.

I apologize though, I'm not great at javascript and so I was wondering if you could maybe just give a pseudo-code explanation of how the tiling works for recreating the full images? I'm comfortable with python and would like to try and build my own little parser.

**Comment by chrisnorth** [comment]
You should be able to find the fullsky images on the same site - if you hover over the boxes, a "fullscreen image" link appears.

As I write this, I realise that this doesnt work on a touch-only device, so that by not help you. 

In terms of the filenaming sequence, each letter gives the quadrant at that "level", with q, r, s, t representing top left, top right, bottom right, bottom left. Sequential letters mean nested quadrants, so longer filenames means a higher zoom level. As I recall, the first level is just t, which is the whole sky with black strips above and below to make it square (you could think of it as a 360x360deg image. So tq.jpg is the top left quadrant of that full image (a 180x180 deg image, with the top half being black and the bottom half showing the top left of the sky) while trs.jpg is the bottom right quadrant of the top right quadrant (a 90 x 90 deg image).

Make sense?

**Comment by chrisnorth** [comment]
Different repo, but have a look at https://github.com/chrisnorth/gravoscope/blob/master/download/cutter.pl which is the perl script @slowe wrote to do the tiling.
